plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags
    prefix: tag_
filters:
  instance-state-name: running
compose:
  ansible_host: private_ip_address 
  public_ip: public_ip_address
  hostname: private_ip_address  
